name: capsula_flutter
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.3
  auto_route: ^10.2.0

  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  protobuf: ^5.0.0
  json_annotation: ^4.9.0
  form_field_validator: ^1.1.0
  url_launcher: ^6.3.2
  iconsax: ^0.0.8
  web_socket_channel: ^3.0.3
  path: ^1.9.0
  path_provider: ^2.1.3
  crypto: ^3.0.5
  drift: ^2.20.3
  sqlite3_flutter_libs: ^0.5.24
  open_filex: ^4.5.0
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  auto_route_generator: ^10.2.5
  json_serializable: ^6.11.1
  drift_dev: ^2.20.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/.env
    - assets/images/
